dbt_lake:
  target: dev
  outputs:
    dev:
      type: athena
      region_name: ap-southeast-2
      work_group: primary
      database: raw
      schema: raw
      s3_staging_dir: s3://de-bootcamp25/
      s3_data_dir:    s3://data-lake-dev-buku/raw/
      threads: 5